/// # Autogenerated dynamic field types
///
/// Dynamic fields can have different types based on the context (e.g. the system call parameters).
/// All the implementations in this module are generated from the C structs and mapped to a Rust
/// enum.
#[allow(missing_docs)]
#[allow(clippy::crate_in_macro_def)]
pub mod dynamic_params;

/// # Event flags
///
/// This module contains the definitions of event flags used in Falco events. These flags are
/// either enums (one value of the enum is set) or bitflags (multiple values can be set at the same time).
#[allow(missing_docs)]
pub mod event_flags;

/// # Event field types
///
/// These are the types that can be used in event fields. They are built-in Rust types wherever
/// possible, newtype wrappers in some cases, or new dedicated types.
pub mod types;
