/// # Autogenerated dynamic field types
///
/// Dynamic fields can have different types based on the context (e.g. the system call parameters).
/// All the implementations in this module are generated from the C structs and mapped to a Rust
/// enum.
#[allow(missing_docs)]
pub mod dynamic_params;
#[allow(missing_docs)]
pub mod event_flags;
pub mod from_bytes;
pub mod to_bytes;
mod type_id;
/// # Event field types
///
/// These are the types that can be used in event fields. They are built-in Rust types wherever
/// possible, newtype wrappers in some cases, or new dedicated types.
pub mod types;

pub use type_id::TypeId;
